### ISSUE TITLE
AutodockActionGoal not working

### ISSUE THREAD

**Issue by Dan07567** [osrf/autodock#16]
I was trying to use follow the instructions for the Mock Robot, when I encountered the following error as I was using the command line "rostopic pub /autodock_action/goal autodock_core/AutoDockingActionGoal {} --once" The error messages are as follows:
![autodock testing failed 2](https://user-images.githubusercontent.com/124703009/218622238-85a64574-6c2a-473c-9ba4-ad877f017b56.JPG)
![autodock testing failed](https://user-images.githubusercontent.com/124703009/218622242-44b52c01-21ae-411c-ad3b-4233ba087286.JPG)

Any tips on this scenario?

**Comment by youliangtan** [comment]
By briefly inspecting your terminal printouts, i dont see any rostopics that are relevant to the `/autodock_action...`. Not sure if the `auto_dock_node` is actually running.

Also to check if the ros msg definition is available in your env, simply do `rosmsg list | grep autodock`

**Comment by JosefGst** [comment]
this worked for me:
```
rostopic pub /autodock_action/goal autodock_core/AutoDockingActionGoal "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
goal_id:
  stamp:
    secs: 0
    nsecs: 0
  id: ''
goal:
  docking_waypoint: ''" --once
```
